/**
 * Glossary rows rendered by the guide page.
 *
 * Lives beside the page rather than inside it because a Next.js page file may
 * only export `default` and the framework's own config keys. Exporting anything
 * else fails the generated page-type check during `next build`, which is a
 * production build failure that `check-types` alone does NOT catch: the types it
 * violates are generated by the build itself and do not exist beforehand.
 *
 * Glossary "Account - what the numbers mean" terms. Extracted to a plain data
 * array (rather than inline JSX) so a test can assert on its content directly
 * without needing to force open the CollapsibleSection it renders inside
 * (closed by default; a static render never reaches its children). Day-trade
 * / PDT count used to be defined here before the product removed that feature
 * - see the day-trade regression test.
 */
export const ACCOUNT_GLOSSARY_TERMS: { term: string; definition: string }[] = [
  {
    term: "Portfolio Value",
    definition: "The total value of your account: all positions plus your cash.",
  },
  {
    term: "Buying Power",
    definition:
      "Your available cash for new positions. This is your non-marginable buying power: the amount Alpaca guarantees works for any stock, marginable or not. Margin accounts may have additional capacity for qualifying securities.",
  },
  {
    term: "Cash",
    definition: "Uninvested money in your account, not tied up in any position.",
  },
  {
    term: "Paper vs Live account",
    definition:
      "Paper trades with fake money to practice; Live trades with real money. The active one is labeled at the top of the trade form.",
  },
];
